# Generated by Django 4.0.4 on 2022-05-05 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryStorage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('location', models.TextField(verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Laboratory Storage',
                'verbose_name_plural': 'Laboratory Storage',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('firstName', models.CharField(max_length=64, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=64, null=True, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=64, verbose_name='Last Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phoneNumber', models.CharField(max_length=16, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('firstName', models.CharField(max_length=64, verbose_name='First Name')),
                ('middleName', models.CharField(blank=True, max_length=64, null=True, verbose_name='Middle Name')),
                ('lastName', models.CharField(max_length=64, verbose_name='Last Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phoneNumber', models.CharField(max_length=16, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Physician',
                'verbose_name_plural': 'Physicians',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('sampleId', models.CharField(max_length=255, verbose_name='Sample ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
    ]
