# Generated by Django 4.0.4 on 2022-05-05 02:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('lastUpdated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('internalId', models.CharField(max_length=255, verbose_name='Internal ID')),
                ('dateSampleTaken', models.DateField(verbose_name='Date Sample Taken')),
                ('status', models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('STORED', 'STORED')], default='RECEIVED', max_length=10)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.physician')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.sample')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
